Щербаков. Задача №2.
maxscherbakov/spbu-python-course pull request #2
Opened 2024-10-08 11:58 UTC by maxscherbakov

2024-10-09 12:59 UTC, Krekep requested changes
Необходимы исправления.

Также моё "фи" Вам. 
1. В readme написано, что пулл-реквест требует описания
2. Я отдельно упоминал об этом на последней паре

2024-10-09 12:59 UTC, Krekep commented on project/curry_uncurry_explicit.py
> +    function: Callable[..., Any], arity: Any
Почему `arity` имеет тип `Any`?

2024-10-09 12:59 UTC, Krekep commented on project/curry_uncurry_explicit.py
> +        return False
Выглядит как ужасный костыль. Вам эта функция вообще не нужна

2024-10-09 12:59 UTC, Krekep commented on project/curry_uncurry_explicit.py
> +    """
В документации должны быть указаны также параметры и возвращаемые значения

2024-10-09 12:59 UTC, Krekep commented on project/decorators.py
> +        argspec = inspect.getfullargspec(function)
Зачем Вам каждый раз получать полную информацию о функции, которая не меняется?

2024-10-09 12:59 UTC, Krekep commented on project/decorators.py
> +                        default_args[i - num_non_default_args], Isolated
Индексацию в этом цикле можно упростить

2024-10-09 12:59 UTC, Krekep commented on project/decorators.py
> +                        list_args.append(default_args[i])
Вам действительно нужно два разных цикла тут?

2024-10-09 12:59 UTC, Krekep commented on tests/test_curry_uncurry_explicit.py
> +        assert uncurry_sum_four(3, 4) == 10
Как минимум не хватает тестов для встроенных в Python функций

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +    def test_cache_fibonacci(self) -> None:
Не хватает тестов:
- со встроенными в Python функциями;
- с нехешируемыми аргументами;
- демонстрирующих кэш после i-той итерации

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +class TestIsolatedEvaluated:
Зачем тут класс? Ну и в целом, остальные классы тоже вызывают вопросы

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +    def test_combination_isolated_evaluated(self) -> None:
Эта функция (как и остальные) никак не использует экземпляр класса, которому принадлежит. Может стоить сделать её статической? Или просто вынести из класса?

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +        assert check_evaluation()[1] != check_evaluation()[1]
Выглядит так, что в 1 из 100 запусков тест будет не проходить

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +    def test_with_position_args(self) -> None:
Не хватает тестов, где не все значения заданы по умолчанию

2024-10-09 12:59 UTC, Krekep commented on tests/test_decorators.py
> +        assert res2[1] == 105
Разделите на несколько блоков (к примеру, работа с res1, а потом работа с res2)

2024-10-10 11:47 UTC, maxscherbakov commented on project/curry_uncurry_explicit.py
> +    function: Callable[..., Any], arity: Any
Подразумевалось, что пользователь мог сильно ошибиться и пережать , например, строку.

2024-10-10 11:48 UTC, maxscherbakov commented on project/curry_uncurry_explicit.py
> +        return False
А эта функция проверяла, что у нас во-первых, число, во-вторых, ≥ 0.

2024-10-10 11:56 UTC, maxscherbakov commented on project/decorators.py
> +        argspec = inspect.getfullargspec(function)
Ошибка.

2024-10-10 11:57 UTC, maxscherbakov commented on project/decorators.py
> +                        list_args.append(default_args[i])
Доработал.

2024-10-10 11:58 UTC, maxscherbakov commented on tests/test_decorators.py
> +class TestIsolatedEvaluated:
Убрал. Можно обойтись и без них.

2024-10-13 08:22 UTC, Krekep requested changes
Необходимы исправления

2024-10-13 08:22 UTC, Krekep commented on tests/test_curry_uncurry_explicit.py
> +    assert curry_explicit(print, 2)(1)(2) is None
Кажется этого здесь не должно быть

2024-10-13 08:22 UTC, Krekep commented on tests/test_decorators.py
> +        s([1, 2, 3])
Этот тест должен успешно проходить

2024-10-13 08:22 UTC, Krekep commented on project/decorators.py
> +                        )
Этот цикл написан очень сложно и запутанно. Перепишите его в более декларативном стиле, с меньшим числом ветвлений.
А ещё в Python есть switch/case

2024-10-13 08:22 UTC, Krekep commented on tests/test_decorators.py
> +    assert check_evaluation()[0] == check_evaluation()[0]
Как этот тест проверяет, что Evaluated запускается, если не указать y?

2024-10-13 08:22 UTC, Krekep commented on tests/test_decorators.py
> +        return a, b, c, x, y, flag, z
А зачем вы их в другом порядке возвращаете?

2024-10-13 08:22 UTC, Krekep commented on tests/test_decorators.py
Нет теста, проверяющего, что Evaluated действительно вызывается каждый раз при вызове функции, а не посчитан единожды

2024-10-13 09:22 UTC, maxscherbakov commented on tests/test_decorators.py
> +        return a, b, c, x, y, flag, z
Так было проще, чтобы добавить проверок, не меняя индексы у имеющихся.

2024-10-13 09:24 UTC, maxscherbakov commented on tests/test_decorators.py
> +    assert check_evaluation()[0] == check_evaluation()[0]
Он проверяет, что без Evaluated значение вычисляется единожды. Тест на запуск Evaluated добавлю.

2024-10-13 09:27 UTC, maxscherbakov commented on tests/test_decorators.py
> +        s([1, 2, 3])
Подойдет ли пердставление кэша двуми списками keys и values (обращаясь по индексам соответсвенно)? Или это должен быть через словарь?

2024-10-16 17:11 UTC, maxscherbakov commented on tests/test_curry_uncurry_explicit.py
> +    assert curry_explicit(print, 2)(1)(2) is None
убрал.

2024-10-16 17:12 UTC, maxscherbakov commented on tests/test_decorators.py
> +        s([1, 2, 3])
исправил

2024-10-16 17:17 UTC, maxscherbakov commented on project/decorators.py
> +                        )
переписал в формате list_args = args + default_args[special_index:]
в цикле проверяется либо элемент Isolated() либо index > Len(args) and Evaluated() и выполняются соответствующие действия.
Подходит ли такое решение?

2024-10-16 17:18 UTC, maxscherbakov commented on tests/test_decorators.py
Добавил

2024-10-18 18:09 UTC, Krekep approved these changes
Зачтено

2024-10-22 10:59 UTC, merged