Щербаков Задача №3
maxscherbakov/spbu-python-course pull request #3
Opened 2024-10-14 16:39 UTC by maxscherbakov

+ [ ] Написать генераторное выражение для четырехмерного набора векторов RGBA модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
+ [ ] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
+ [ ] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

2024-10-15 09:28 UTC, Krekep requested changes
Необходимы небольшие изменения

2024-10-15 09:28 UTC, Krekep commented on project/generators/primes_generator.py
> +        num += 1
С одной стороны это решение работает быстрее наивного, но с другой стороны оно требует дополнительной (и не константой) памяти.
Суть этого генератора в том, что он может сгенерировать бесконечную последовательность простых чисел, но добавив в него массив, в котором хранятся найденный простые, Вы ограничили размер последовательности.
Перепишите его без использования массива с простыми числами

2024-10-15 09:28 UTC, Krekep commented on project/generators/rgba_generator.py
> +        (r, g, b, a * 2)
Формально Вы правы, но перепишите с использованием `if` для демонстрации того, что Вы это умеете

2024-10-15 09:28 UTC, Krekep commented on project/generators/primes_generator.py
> +    gen = function()
Зачем Вам отдельная переменная?

2024-10-15 09:28 UTC, Krekep commented on project/generators/primes_generator.py
> +            raise IndexError(f"The index must be greater than {n}")
Почему обязательно больше?

2024-10-15 10:40 UTC, maxscherbakov commented on project/generators/primes_generator.py
> +            raise IndexError(f"The index must be greater than {n}")
Потому что генератор идет только вперед и дважды получить, например, 5-й элемент не получится.

2024-10-15 10:47 UTC, Krekep commented on project/generators/primes_generator.py
> +            raise IndexError(f"The index must be greater than {n}")
Но Вам необязательно переходить к следующему числу, если вы хотите дважды получить 5-ое простое число

2024-10-15 10:56 UTC, maxscherbakov commented on project/generators/primes_generator.py
> +            raise IndexError(f"The index must be greater than {n}")
Подойдет ли решение с хранением последнего числа?

2024-10-15 11:00 UTC, Krekep commented on project/generators/primes_generator.py
> +            raise IndexError(f"The index must be greater than {n}")
Да

2024-10-15 11:17 UTC, maxscherbakov commented on project/generators/primes_generator.py
> +    gen = function()
Чтобы запустить генератор.

2024-10-15 13:23 UTC, maxscherbakov commented on project/generators/primes_generator.py
> +        num += 1
Переписал

2024-10-15 15:56 UTC, Krekep commented
Не выполнены формальные требования к оформлению Pull-request

2024-10-15 17:11 UTC, maxscherbakov commented on project/generators/rgba_generator.py
> +        (r, g, b, a * 2)
переписал

2024-10-18 18:10 UTC, Krekep approved these changes
Зачтено

2024-10-22 10:59 UTC, merged