Щербаков Задача №4
maxscherbakov/spbu-python-course pull request #4
Opened 2024-10-22 16:42 UTC by maxscherbakov

# Задача 4. Пул потоков

- [ ] Реализовать паттерн "пул потоков".
  - [ ] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [ ] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [ ] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [ ] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [ ] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [ ] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [ ] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [ ] Допущения:
    - Использование класса для реализации пула потоков необязательно
- [ ] **(Доп., +2 балла)** С помощью `concurrent.futures` реализовать параллельное вычисление суммы полного декартового произведения множества целых чисел

2024-10-22 17:23 UTC, Krekep requested changes
В целом всё хорошо, но немного доделать надо

2024-10-22 17:23 UTC, Krekep commented on project/thread_pool.py
> +        self._task_queue: Queue[TaskWrapper] = Queue()
Этот класс реализует в себе методы для работы с потоками. Из пакетов для работы с многопоточностью по условию задачи разрешён только `threading`

2024-10-22 17:23 UTC, Krekep commented on tests/test_thread_pool.py
Не хватает теста проверяющего, что действительно в данный момент времени существует `n` работающих, активных потока

2024-10-22 17:43 UTC, maxscherbakov commented on tests/test_thread_pool.py
Этот тест есть, test_thread_count. Он самый последний в файле.

2024-10-22 17:50 UTC, maxscherbakov commented on project/thread_pool.py
> +        self._task_queue: Queue[TaskWrapper] = Queue()
Заменил на list. Добавил уведомления потоков. Понял почему queue не подходил под условие.

2024-10-23 07:47 UTC, Krekep approved these changes
Зачтено

2024-10-23 10:34 UTC, merged