Щербаков Задача №5
maxscherbakov/spbu-python-course pull request #5
Opened 2024-10-28 12:01 UTC by maxscherbakov

# Задача 5. Игра

* **Дедлайн**: 31.10.2024, 23:59
* Полный балл: 13

## Задача

- [ ] Реализовать одну из игр в списке ниже. Вариант определяется как длина Вашего ФИО по модулю 2 плюс 1
  1. [рулетка](https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%BB%D0%B5%D1%82%D0%BA%D0%B0)
  2. [блэкджек](https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D1%8D%D0%BA%D0%B4%D0%B6%D0%B5%D0%BA)
- Пример выбора варианта
  - len(Алимов Павел Геннадьевич) = 6 + 5 + 11 = 22
  - 22 % 2 = 0
  - 0 + 1 = 1 -> вариант 1
-------------------
  - Требования:
    - [ ] Должно быть как минимум три различных стратегии игры ботов
    - [ ] Должны быть методы, показывающие текущее состояние игры
    - [ ] На каждую сущность должен быть свой класс
  - Ограничения:
    - Игра ведётся либо до победы одного/нескольких участников, либо до заданного количества шагов
  - Допущения:
    - Реализовывать Игрока необязательно. Достаточно того, что в игре будут участвовать только боты
    - Графический интерфейс необязателен. Информацию достаточно выводить в консоль
  - Проверка:
    - Будет проверяться декомпозиция на классы
    - Тесты должны отображать
      - Что состояние игры меняется с течением времени
      - Работоспособность методов влияющих на состояние игры
      - Может быть что-то ещё, тестов много не бывает
    - Надо добавить пример работы игры с выводом информации о состоянии в каждом раунде. Для примеров лучше создать отдельную папку `examples`
- [ ] **(Доп., +5 балла)** Для реализованной игры построить [UML диаграмму классов](https://en.wikipedia.org/wiki/Class_diagram)
- [ ] **(Доп., +5 балла)** С помощью метаклассов добавить стратегию бота и поменять правила игры (к примеру, количество полей или условия победы)

2024-10-28 15:03 UTC, Krekep requested changes
В целом хорошо, но небольшие правки нужны

2024-10-28 15:03 UTC, Krekep commented on project/game/exemple/exemple.py
example

2024-10-28 15:03 UTC, Krekep commented on project/game/src/desk.py
> +            self.check_bet(id_player, bet)
Этот метод возвращает True/False, которые дальше не используются. Добавьте корректную проверку, что игрок может поставить ставку

2024-10-28 15:03 UTC, Krekep commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
У руки всё-таки должно быть явное количество очков, а не одно из множества

2024-10-28 15:19 UTC, maxscherbakov commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Но ведь туз может считаться как 1 так и 11, поэтому тут множество возможных очков. Если нужно явно, то какое выбирать?

2024-10-28 15:54 UTC, maxscherbakov commented on project/game/exemple/exemple.py
Исправил

2024-10-28 15:56 UTC, maxscherbakov commented on project/game/src/desk.py
> +            self.check_bet(id_player, bet)
Добавил корректную проверку.

2024-10-28 15:57 UTC, maxscherbakov commented on project/game/exemple/exemple.py
Исправил.

2024-10-28 16:53 UTC, Krekep commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Я сам никогда не играл в блэкджек, но на википедии написано, что туз засчитывается за 11 очков, пока общая сумма меньше 21, дальше за 1 очко

2024-10-28 16:56 UTC, Krekep commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Просто в реальной игре вряд ли говорят --- "у Вас тут либо 2, либо 12, либо 22 очка, выбирайте сами". Скорее всего говорят точное количество очков. Если есть какие-то спорные моменты по начислению очков, то можете зафиксировать какой-то вариант, необязательно строгое соответствие правилам

2024-10-28 17:02 UTC, maxscherbakov commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Подойдет ли вариант с хранением множества возвожных, но метод get_score() возвращает максимальное <= 21?
Просто если выбрать одно, то может получиться ситуация, в которой у игрока могло быть 23 или 13, а он считается проигравшим.

2024-10-28 17:07 UTC, Krekep commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Так у него не могло быть 23, т.к. общая сумма больше 21, соответственно считается, что туз это 1 очко и его сумма равна 13.
Вроде `максимальное <= 21` подходит под правила

2024-10-28 17:18 UTC, maxscherbakov commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
Подойдет ли решение, в котором руке присваивается конкретное количество очков, но у самой карты туза останется два значения в scores?

2024-10-28 17:31 UTC, maxscherbakov commented on tests/blackjak/test_blackjak.py
> +        ([A, K], [J, six], {11, 21}, {16}),
В итоге остановился на идее не хранить в классе Card счет. Счет будет только у руки.

2024-10-30 08:50 UTC, Krekep requested changes
Выглядит хорошо, но не могу пока зачесть UML диаграмму классов и по коду надо сделать косметические правки

2024-10-30 08:50 UTC, Krekep commented on project/game/docs/UML.png
Странно, что `Card` не соединён с `Deck`, хотя используется там. Также у Вас все поля и методы публичные, что нарушает принцип инкапсуляции

2024-10-30 08:50 UTC, Krekep commented on project/game/examples/example.txt
> +Рука дилера:
Сделайте весь вывод на английском

2024-10-30 08:50 UTC, Krekep commented on project/game/src/game.py
> +        print()
Лучше замените на один print, в котором два раза делаете перевод строки

2024-10-30 08:50 UTC, Krekep commented on project/game/src/strategies.py
> +def check_split(cards: list[Card], dealer_card_name: str) -> Action | None:
Не хватает документации для этой и функций ниже

2024-10-30 09:02 UTC, maxscherbakov commented on project/game/src/game.py
> +        print()
Заменил

2024-10-30 09:03 UTC, maxscherbakov commented on project/game/examples/example.txt
> +Рука дилера:
Исправил.

2024-10-30 09:12 UTC, maxscherbakov commented on project/game/src/strategies.py
> +def check_split(cards: list[Card], dealer_card_name: str) -> Action | None:
Добавил документацию к функциям.

2024-10-30 10:32 UTC, maxscherbakov commented on project/game/docs/UML.png
Соединил. Поправил обозначения для приватных методов и полей.

2024-11-01 16:07 UTC, Krekep approved these changes
Зачтено

2024-11-01 16:32 UTC, merged